# Travis-CI config
language: node_js
node_js: stable

# Cache dir config
cache:
  directories:
    - node_modules

# Install scripts
install:
  - npm install

#before_script:
script:
  - hexo g

# Build LifeCycle
after_script:
  - cd ./public
  - git init
  - git config user.name "ntnyq"
  - git config user.email "ntnyq13@gmail.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-page

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ntnyq/ntnyq.github.io.git
